package:
  name: autocut
  version: "0.0.4"

source:
  git_rev: develop
  git_url: https://github.com/siruix/autocut.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - autocut

about:
  home: https://github.com/siruix/autocut
  license: BSD
  license_file: LICENSE